version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: node_fulltask_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234567@a$'
      MYSQL_DATABASE: 'node_fulltask'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
